Repository depromeet/Took-FE, pull requests merged in 2025-03, with the labels that each got.

#43 [Feat] 공통 컴포넌트 구현(Toast) / 스타일 수정(Input) / 디자인 시스템 수정
  package.json
  pnpm-lock.yaml
  public/icons/Frame.svg
  public/icons/alarmIcon.svg
  public/icons/avatarIcon.svg
  public/icons/credit-card.svg
  public/icons/deleteIcon.svg
  public/icons/logo.svg
  public/icons/menuIcon.svg
  public/icons/prevIcon.svg
  public/icons/sonnerIcon.svg
  public/icons/user.svg
  src/app/globals.css
  src/app/page.tsx
  src/shared/ui/Input/index.tsx
  src/shared/ui/Input/input.tsx
  src/shared/ui/Input/inputBody.tsx
  src/shared/ui/Input/inputLabel.tsx
  src/shared/ui/Toast/index.tsx
  src/shared/ui/Toast/sonner.tsx
  src/shared/ui/footer.tsx
  src/shared/ui/tab.tsx
  src/shared/ui/typography/typography.ts
  tailwind.config.ts
Labels: 🚀 feature

#42 [feat] 공통 컴포넌트(tag , indicator) 구현
  package.json
  pnpm-lock.yaml
  public/icon/closeBtn.svg
  src/shared/ui/progressBar/index.tsx
  src/shared/ui/progressBar/progress.tsx
  src/shared/ui/tag/tag.tsx
  tailwind.config.ts
Labels: 🚀 feature

#39 [feat] 로그인 온보딩 디자인 구현
  package.json
  pnpm-lock.yaml
  public/images/login/onboarding/onboarding-1.png
  public/images/login/onboarding/onboarding-2.png
  public/images/login/onboarding/onboarding-3.png
  public/images/login/onboarding/onboarding-bg.png
  public/images/login/onboarding/onboarding-login.png
  src/app/login/page.tsx
  src/features/auth/login/ui/LoginFeature.tsx
  src/features/auth/ui/KakaoLoginButton.tsx
  src/features/onboarding/config/slides.ts
  src/features/onboarding/ui/OnboardingCarousel.tsx
  src/features/onboarding/ui/OnboardingFeature.tsx
  src/features/onboarding/ui/OnboardingHeader.tsx
  src/features/onboarding/ui/OnboardingSlide.tsx
Labels: 🚀 feature

#40 [feat] Axios & React Query
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/page.tsx
  src/features/home/hooks/sample.ts
  src/shared/apis/client.ts
  src/shared/apis/preventClientMultipleRefreshToken.ts
  src/shared/apis/preventServerMultipleRefreshToken.ts
  src/shared/apis/server.ts
  src/shared/constants/index.ts
  src/shared/providers/QueryClientProvider.tsx
  src/shared/providers/index.tsx
Labels: 🚀 feature

#48 feat: 공통 컴포넌트 - 리스트 구현
  package.json
  src/shared/spacing/spacing.ts
  src/shared/ui/icon/Arrow.svg
  src/shared/ui/icon/Union.svg
  src/shared/ui/list/index.tsx
  src/shared/ui/list/wrappedList.tsx
  tailwind.config.ts
Labels: ✅ Auto approve, 🚀 feature, 💄 style

#50 [chore] pnpm version 고정
  package.json
  pnpm-lock.yaml
Labels: auto approve

#52 [Feat] 공통 컴포넌트 구현(Header, Appbar) / 스타일 수정(Button, Avatar)
  src/app/page.tsx
  src/shared/ui/Avatar/avatar.tsx
  src/shared/ui/Avatar/index.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/avatar.tsx
  src/shared/ui/button.tsx
  src/shared/ui/header.tsx
  tailwind.config.ts
Labels: auto approve, 🚀 feature

#55 [Feat] 공통 컴포넌트 구현 - Img, Thumbnail
  public/icons/imageIcon.svg
  src/app/page.tsx
  src/shared/config.ts
  src/shared/ui/img.tsx
  src/shared/ui/thumbnail.tsx
Labels: 🚀 feature

#57 [feat] 카드 생성 온보딩 페이지, Multi-step-form (진행중)
  public/icons/avatar-add-image.svg
  public/icons/leftArrow.svg
  public/icons/rightArrow.svg
  public/icons/unionIcon.svg
  src/app/(create)/card-create/new-card/multi-step-form/page.tsx
  src/app/(create)/card-create/new-card/page.tsx
  src/app/(create)/card-create/page.tsx
  src/features/card-create/config/index.ts
  src/features/card-create/index.ts
  src/features/card-create/ui/index.tsx
  src/features/card-create/ui/onBoardingView.tsx
  src/features/multi-step-form/components/AvartarImg.tsx
  src/features/multi-step-form/config/index.ts
  src/features/multi-step-form/index.tsx
  src/features/multi-step-form/ui/careerForm/firstStep.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/careerForm/thridStep.tsx
  src/features/multi-step-form/ui/careerForm/twoStep.tsx
  src/features/multi-step-form/ui/index.tsx
  src/features/new-card/config/index.tsx
  src/features/new-card/index.tsx
  src/features/new-card/ui/index.tsx
  src/features/new-card/ui/newCreateCardView.tsx
  src/shared/hooks/useHistoryBack.ts
  src/shared/ui/Avatar/imageAdd.tsx
  src/shared/ui/Avatar/index.tsx
  src/shared/ui/Input/index.tsx
  src/shared/ui/button.tsx
  src/shared/ui/list/index.tsx
  src/shared/ui/list/wrappedList.tsx
Labels: auto approve, 🚀 feature, ♻️ refactor

#59 [feat] 카드 생성 멀티스텝 폼 1차 구현
  @types/webview.d.ts
  package.json
  pnpm-lock.yaml
  src/features/multi-step-form/config/index.ts
  src/features/multi-step-form/schema/index.ts
  src/features/multi-step-form/ui/careerForm/errorMsg.tsx
  src/features/multi-step-form/ui/careerForm/firstStep.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/careerForm/twoStep.tsx
  src/features/multi-step-form/ui/index.tsx
  src/shared/hooks/useDevice.ts
  src/shared/ui/Input/index.tsx
Labels: auto approve, 🚀 feature

#60 [develop] maximum scale 및 pinch zoom 고정
  src/app/layout.tsx
Labels: auto approve

#61 [Feat] 선택 태그 화면 UI 구현
  public/icons/icon_graphic_large.png
  public/images/tag/background.png
  public/images/tag/ball.png
  src/features/multi-step-form/ui/careerForm/firstStep.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/careerForm/secondStep.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/config/config.ts
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/Ball.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/TagBox.tsx
  src/shared/ui/header.tsx
  src/shared/ui/tag/tag.tsx
Labels: auto approve

#63 [Refactor] 공통 컴포넌트 use client 지정
  src/shared/ui/Avatar/avatar.tsx
  src/shared/ui/Avatar/index.tsx
  src/shared/ui/Input/index.tsx
  src/shared/ui/Input/input.tsx
  src/shared/ui/Toast/index.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/button.tsx
  src/shared/ui/card.tsx
  src/shared/ui/footer.tsx
  src/shared/ui/header.tsx
  src/shared/ui/img.tsx
  src/shared/ui/list/index.tsx
  src/shared/ui/list/wrappedList.tsx
  src/shared/ui/tab.tsx
  src/shared/ui/thumbnail.tsx
  src/shared/ui/typography/index.tsx
Labels: auto approve

#65 [Design] Appbar padding 20px 로 일괄 지정
  src/shared/ui/appbar.tsx
Labels: auto approve

#66 [Feat] 선택 태그 화면 기능 구현
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/careerForm/secondStep.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/config/config.ts
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/Ball.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/TagBox.tsx
  src/features/multi-step-form/ui/index.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/header.tsx
Labels: auto approve

#67 [Feat] currentStep과 선택한 태그의 개수에 따른 버튼 조건부 렌더링 구현
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/careerForm/secondStep.tsx
  src/shared/ui/appbar.tsx
Labels: auto approve, 🚀 feature

#69 [Feat] 홈화면 카드 스와이퍼 영역 구현 (wip)
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/page.tsx
  src/features/home/components/BusinessCard/AddCard.tsx
  src/features/home/components/BusinessCard/Background/AddCradBackground.tsx
  src/features/home/components/BusinessCard/Background/DesignerCardBackground.tsx
  src/features/home/components/BusinessCard/Background/DeveloperCardBackground.tsx
  src/features/home/components/BusinessCard/Card.tsx
  src/features/home/components/BusinessCard/CardTag.tsx
  src/features/home/components/icons/CardPlusIcon.tsx
  src/features/home/components/icons/DesignerIcon.tsx
  src/features/home/components/icons/DeveloperIcon.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/home/hooks/prefetches/useCardPrefetch.ts
  src/features/home/hooks/queries/useCardQuery.ts
  src/features/home/mocks/index.ts
  src/features/home/providers/CardSwiperProvider.tsx
  src/features/home/providers/SwiperSlideProvider.tsx
  src/features/home/types/index.ts
  src/shared/ui/card.tsx
  tailwind.config.ts
Labels: auto approve

#72 [Feat] 대표 썸네일 페이지 UI 구현, 선택 태그 페이지 인터렉션 구현(선택 태그 이동 제외)
  src/app/globals.css
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/careerForm/secondStep.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/config/config.ts
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/Ball.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/TagBox.tsx
  src/shared/ui/header.tsx
  src/shared/ui/thumbnail.tsx
Labels: auto approve, 🚀 feature, 💄 style

#70 [feat] 카카오 로그인 버튼 구현
  public/icons/apple-icon.svg
  public/icons/google-icon.svg
  public/icons/kakao-icon.svg
  src/app/auth/[provider]/page.tsx
  src/app/main/page.tsx
  src/features/auth/login/apis/getToken.ts
  src/features/auth/login/config/loginProviderConfig.ts
  src/features/auth/login/model/providers/kakao.ts
  src/features/auth/login/types/auth.ts
  src/features/auth/login/ui/LoginButton.tsx
  src/features/auth/login/ui/LoginFeature.tsx
  src/features/auth/model/index.ts
  src/features/auth/ui/KakaoLoginButton.tsx
  src/features/home/hooks/queries/useCardQuery.ts
  src/features/home/hooks/sample.ts
  src/shared/apis/client.ts
  src/shared/apis/preventClientMultipleRefreshToken.ts
  src/shared/constants/index.ts
Labels: 🚀 feature

#79 💄 Style: 선택된 태그 이동하는 애니메이션 구현 완성
  src/app/globals.css
  src/features/multi-step-form/ui/careerForm/tagFormStep/config/config.ts
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/TagBox.tsx
  src/shared/ui/tag/tag.tsx
Labels: auto approve, 💄 style

#81 [feat] navbar 구현
  src/app/page.tsx
  src/shared/ui/Navigation/icons/MyCardIcon.tsx
  src/shared/ui/Navigation/icons/ReceivedCardIcon.tsx
  src/shared/ui/Navigation/icons/SettingIcon.tsx
  src/shared/ui/Navigation/index.tsx
Labels: auto approve

#78 [feat] 카카오 , 구글 로그인 구현 완료
  src/app/api/auth/callback/[provider]/page.tsx
  src/app/main/page.tsx
  src/features/auth/login/config/authConfig.ts
  src/features/auth/login/config/loginProviderConfig.ts
  src/features/auth/login/model/providers/kakao.ts
  src/features/auth/login/ui/LoginButton.tsx
  src/features/auth/login/utils/envVaild.ts
Labels: 🚀 feature

#74 [feat] 명함 상세 페이지 구현
  package.json
  pnpm-lock.yaml
  public/icons/designer-icon-white.svg
  public/icons/developer-icon-white.svg
  public/icons/leftArrow-white.svg
  public/icons/menuIcon-white.svg
  public/icons/region.svg
  public/icons/sns-icon/behance.svg
  public/icons/sns-icon/brunch.svg
  public/icons/sns-icon/github.svg
  public/icons/sns-icon/instagram.svg
  public/icons/sns-icon/linkedin.svg
  public/icons/sns-icon/naver_blog.svg
  public/icons/sns-icon/tistory.svg
  public/icons/sns-icon/velog.svg
  public/images/card-detail/card-detail-design.png
  public/images/card-detail/card-detail-develop.png
  src/app/(detail)/card-detail/[cardId]/page.tsx
  src/features/card-detail/config/jobs-config.ts
  src/features/card-detail/config/sns-config.ts
  src/features/card-detail/config/tabs-config.ts
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/hooks/useScrollPosition.ts
  src/features/card-detail/hooks/useTabsActive.ts
  src/features/card-detail/mocks/sample.ts
  src/features/card-detail/types/cardDetail.ts
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/cardTabs.tsx
  src/features/card-detail/ui/domain.tsx
  src/features/card-detail/ui/hobby.tsx
  src/features/card-detail/ui/posts.tsx
  src/features/card-detail/ui/projects.tsx
  src/features/card-detail/ui/recent.tsx
  src/features/card-detail/ui/sns.tsx
  src/features/card-detail/ui/underlineTabs.tsx
  src/shared/spacing/spacing.ts
  src/shared/ui/appbar.tsx
  src/shared/ui/postThumbnail.tsx
  tailwind.config.ts
Labels: 🚀 feature

#83 [feat] 로그인 미들웨어 설정
  src/middleware.ts
Labels: 🚀 feature

#91 🐛 Fix: 배포 env 백엔드 API 수정
  src/shared/constants/index.ts
Labels: auto approve

#92 🐛 Fix: 배포 env 백엔드 API 수정 (#91)
  src/shared/constants/index.ts
Labels: auto approve

#93 [Feat] 공통 컴포넌트 Appbar, Toast 편집
  public/icons/searchIcon.svg
  public/icons/toast-icon/checkIcon.svg
  public/icons/toast-icon/warningIcon.svg
  src/shared/ui/Toast/index.tsx
  src/shared/ui/appbar.tsx
Labels: auto approve, 🚀 feature

#97 ✨ Feat: 설정 리스트 view 구현
  src/app/setting/page.tsx
  src/features/setting/index.ts
  src/features/setting/ui/index.tsx
Labels: auto approve, 🚀 feature

#103 [feat]: 회원 탈퇴 페이지 UI 구현, react hook form 구현
  src/app/(create)/card-create/page.tsx
  src/app/setting/user-quit/page.tsx
  src/features/setting/config/index.ts
  src/features/setting/index.ts
  src/features/setting/schema/index.ts
  src/features/setting/ui/index.tsx
  src/features/setting/ui/userQuit.tsx
  src/shared/ui/button/fixedButton.tsx
  src/shared/ui/checkbox.tsx
Labels: auto approve

#105 [feat] 알람 설정 UI 구현
  src/app/setting/alram/page.tsx
  src/features/setting/index.ts
  src/features/setting/ui/alram.tsx
  src/features/setting/ui/index.tsx
  src/shared/ui/list/index.tsx
Labels: auto approve, 🚀 feature

#100 [feat] 받은 명함 상세 페이지 디자인 구현
  next.config.mjs
  public/icons/delete.svg
  public/icons/edit.svg
  src/app/(detail)/card-detail/[cardId]/page.tsx
  src/app/api/auth/callback/[provider]/page.tsx
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/hooks/useBottomModal.ts
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/types/cardDetail.ts
  src/features/card-detail/types/myCard.ts
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/cardTabs.tsx
  src/features/card-detail/ui/domain.tsx
  src/features/card-detail/ui/hobby.tsx
  src/features/card-detail/ui/posts.tsx
  src/features/card-detail/ui/projects.tsx
  src/features/card-detail/ui/recent.tsx
  src/shared/ui/bottomModal/bottomModal.tsx
  src/shared/ui/bottomModal/bottomModalItem.tsx
  src/shared/ui/bottomModal/bottomModalTitle.tsx
  src/shared/ui/bottomModal/memoInput.tsx
Labels: 🚀 feature

#109 [Feat] 명함 생성 - 메인화면 UI 구현
  package.json
  pnpm-lock.yaml
  public/icons/downArrow.svg
  public/icons/folderIcon.svg
  public/icons/toast-icon/sonnerIcon.svg
  src/app/(received)/received/page.tsx
  src/features/home/types/index.ts
  src/features/received/config/index.ts
  src/features/received/model/queries/useReceivedCardQuery.ts
  src/features/received/ui/index.tsx
  src/features/received/ui/receivedCard.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/thumbnail.tsx
  tailwind.config.ts
Labels: auto approve, 🚀 feature

#110 [Feat] Apple login 구현
  src/app/api/auth/callback/[provider]/page.tsx
  src/features/auth/login/config/authConfig.ts
Labels: auto approve

#99 [Feat] Onboarding 페이지 UI 수정 및 이미지 교체
  public/images/login/onboarding/onboarding-1.png
  public/images/login/onboarding/onboarding-2.png
  public/images/login/onboarding/onboarding-3.png
  public/images/login/onboarding/onboarding-4.png
  public/images/login/onboarding/onboarding-bg.png
  src/app/globals.css
  src/app/login/page.tsx
  src/app/onboarding/page.tsx
  src/features/auth/login/ui/LoginFeature.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/onboarding/components/FirstOnboarding/DecoAura.tsx
  src/features/onboarding/components/FirstOnboarding/DecoCircle.tsx
  src/features/onboarding/components/FirstOnboarding/FirstBackground.tsx
  src/features/onboarding/components/FirstOnboarding/TagGroup.tsx
  src/features/onboarding/components/SecondOnboarding/DecoCard.tsx
  src/features/onboarding/components/SecondOnboarding/DecoCircle.tsx
  src/features/onboarding/components/SecondOnboarding/SecondBackground.tsx
  src/features/onboarding/components/ThirdOnboarding/DecoCards.tsx
  src/features/onboarding/components/ThirdOnboarding/DecoCircle.tsx
  src/features/onboarding/components/ThirdOnboarding/DeveloperCard/DecoDesignerCard.tsx
  src/features/onboarding/components/ThirdOnboarding/DeveloperCard/DecoDeveloperCard.tsx
  src/features/onboarding/components/ThirdOnboarding/ThirdBackground.tsx
  src/features/onboarding/config/slides.ts
  src/features/onboarding/config/slides.tsx
  src/features/onboarding/containers/BackgroundContainer.tsx
  src/features/onboarding/containers/FirstOnboardingContainer.tsx
  src/features/onboarding/containers/SecondOnboardingContainer.tsx
  src/features/onboarding/containers/ThirdOnboardingContainer.tsx
  src/features/onboarding/screen/index.tsx
  src/features/onboarding/ui/OnboardingCarousel.tsx
  src/features/onboarding/ui/OnboardingFeature.tsx
  src/features/onboarding/ui/OnboardingHeader.tsx
  src/features/onboarding/ui/OnboardingSlide.tsx
  src/middleware.ts
  tailwind.config.ts
Labels: auto approve, ♻️ refactor

#112 debug
  src/features/multi-step-form/components/AvartarImg.tsx
  src/features/multi-step-form/hooks/queries/useCreateCard.ts
  src/features/multi-step-form/schema/index.ts
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/multi-step-form/ui/careerForm/secondStep.tsx
Labels: auto approve, ♻️ refactor

#113 debug (#112)
  src/features/multi-step-form/components/AvartarImg.tsx
  src/features/multi-step-form/hooks/queries/useCreateCard.ts
  src/features/multi-step-form/schema/index.ts
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/multi-step-form/ui/careerForm/secondStep.tsx
Labels: auto approve

#114 Refactor/change onboarding
  src/features/auth/login/ui/LoginFeature.tsx
  src/features/login/components/Background.tsx
  src/features/login/components/DecoAura.tsx
  src/features/login/components/DecoDesignerCircle.tsx
  src/features/login/components/DecoDesignerLogo.tsx
  src/features/login/components/DecoDeveloperCircle.tsx
  src/features/login/components/DecoDeveloperLogo.tsx
  src/features/login/components/TookLogo.tsx
  src/features/login/components/TopBlur.tsx
  src/features/login/containers/LoginBackgroundContainer.tsx
Labels: auto approve

#115 [feature] 로그인 화면 배경 구현
  src/features/auth/login/ui/LoginFeature.tsx
  src/features/login/components/Background.tsx
  src/features/login/components/DecoAura.tsx
  src/features/login/components/DecoDesignerCircle.tsx
  src/features/login/components/DecoDesignerLogo.tsx
  src/features/login/components/DecoDeveloperCircle.tsx
  src/features/login/components/DecoDeveloperLogo.tsx
  src/features/login/components/TookLogo.tsx
  src/features/login/components/TopBlur.tsx
  src/features/login/containers/LoginBackgroundContainer.tsx
Labels: auto approve

#119 [feat] 이용약관 페이지 구현
  src/app/globals.css
  src/app/setting/terms/page.tsx
  src/features/setting/index.ts
  src/features/setting/ui/index.tsx
  src/features/setting/ui/terms.tsx
  src/shared/ui/appbar.tsx
  tailwind.config.ts
Labels: auto approve, 🚀 feature

#120 [feat] 개인정보 약관 페이지 구현
  src/app/setting/privacy-terms/page.tsx
  src/features/setting/ui/index.tsx
  src/features/setting/ui/privacyTerms.tsx
Labels: auto approve, 🚀 feature

#121 fix: 다크모드, 라이트 모드 제거
  src/app/globals.css
  src/features/setting/ui/index.tsx
  src/features/setting/ui/privacyTerms.tsx
Labels: auto approve, 💄 style

#123 [feat] 구글 로그인 브릿지 적용
  src/features/auth/login/ui/LoginButton.tsx
  src/features/auth/login/utils/nativeBridge.ts
Labels: auto approve, 🚀 feature

#116 [Refactor] apple login 방식 수정
  src/app/api/auth/callback/[provider]/page.tsx
  src/app/api/auth/callback/[provider]/route.ts
  src/features/auth/login/config/authConfig.ts
  src/shared/apis/client.ts
  src/shared/apis/server.ts
Labels: auto approve

#125 [feat] 받은 명함 상세 페이지 Empty 컴포넌트 추가
  src/app/api/auth/callback/[provider]/route.ts
  src/features/card-detail/components/empty.tsx
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/cardTabs.tsx
  src/features/card-detail/ui/domain.tsx
  src/features/card-detail/ui/posts.tsx
  src/features/card-detail/ui/projects.tsx
  src/features/card-detail/ui/recent.tsx
  src/features/card-detail/ui/sns.tsx
Labels: 🚀 feature

#129 debug: 카드 생성 페이지 디버깅
  src/app/(create)/card-create/new-card/multi-step-form/page.tsx
  src/app/(create)/card-create/new-card/page.tsx
  src/app/(create)/card-create/page.tsx
  src/features/multi-step-form/components/AvartarImg.tsx
  src/features/multi-step-form/config/index.ts
  src/features/multi-step-form/hooks/queries/useCreateCard.ts
  src/features/multi-step-form/ui/careerForm/config/index.ts
  src/features/multi-step-form/ui/careerForm/constants/index.ts
  src/features/multi-step-form/ui/careerForm/firstStep.tsx
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/careerForm/secondStep.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/Ball.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/MotionTagBox.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/TagBox.tsx
  src/features/multi-step-form/ui/careerForm/thridStep.tsx
  src/features/multi-step-form/ui/index.tsx
  src/features/multi-step-form/utils/index.tsx
  src/shared/config.ts
  src/shared/store/cardFormState.ts
Labels: auto approve, 🐛 bug

#133 배포 1.0.2
  src/app/(create)/card-create/new-card/multi-step-form/page.tsx
  src/app/(create)/card-create/new-card/page.tsx
  src/app/(create)/card-create/page.tsx
  src/app/api/auth/callback/[provider]/route.ts
  src/features/card-detail/components/empty.tsx
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/cardTabs.tsx
  src/features/card-detail/ui/domain.tsx
  src/features/card-detail/ui/posts.tsx
  src/features/card-detail/ui/projects.tsx
  src/features/card-detail/ui/recent.tsx
  src/features/card-detail/ui/sns.tsx
  src/features/multi-step-form/components/AvartarImg.tsx
  src/features/multi-step-form/config/index.ts
  src/features/multi-step-form/hooks/queries/useCreateCard.ts
  src/features/multi-step-form/ui/careerForm/config/index.ts
  src/features/multi-step-form/ui/careerForm/constants/index.ts
  src/features/multi-step-form/ui/careerForm/firstStep.tsx
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/careerForm/secondStep.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/Ball.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/MotionTagBox.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/TagBox.tsx
  src/features/multi-step-form/ui/careerForm/thridStep.tsx
  src/features/multi-step-form/ui/index.tsx
  src/features/multi-step-form/utils/index.tsx
  src/shared/config.ts
  src/shared/store/cardFormState.ts
Labels: auto approve, 🐛 bug

#130 [Feat] 명함 상세 페이지 - 명함 선택, 폴더 설정, 명함 삭제 UI 구현
  package.json
  pnpm-lock.yaml
  public/icons/addIcon.svg
  public/images/received/banner.png
  public/images/received/banner.webp
  src/app/(received)/received/interesting/page.tsx
  src/app/(received)/received/page.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/config/config.ts
  src/features/received/config/index.ts
  src/features/received/model/queries/useFoldersQuery.ts
  src/features/received/model/useModal.ts
  src/features/received/ui/chooseReceivedCardView.tsx
  src/features/received/ui/index.tsx
  src/features/received/ui/intellibanner.tsx
  src/features/received/ui/receivedCard.tsx
  src/features/received/ui/receivedCardView.tsx
  src/shared/ui/Checkbox/receivedCheckbox.tsx
  src/shared/ui/Navigation/index.tsx
  src/shared/ui/Toast/index.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/bottomModal/bottomModal.tsx
  src/shared/ui/bottomModal/bottomModalItem.tsx
  src/shared/ui/dialog/index.tsx
  src/shared/ui/header.tsx
  src/shared/ui/img.tsx
  src/shared/ui/thumbnail.tsx
  tailwind.config.ts
Labels: auto approve, 🚀 feature

#138 [feat] 명함 공유 애니메이션 구현
  src/app/(share)/card-share/page.tsx
  src/features/share/components/ShareCard.tsx
  src/features/share/components/ShareCardTag.tsx
  src/features/share/components/background/DesignerCardBackground.tsx
  src/features/share/components/background/DeveloperCardBackground.tsx
  src/features/share/components/background/ShareBackground.tsx
  src/features/share/container/AnimatedShareCardWrapper.tsx
  src/features/share/container/ShareCardContentContainer.tsx
  src/features/share/container/ShareClipboardContainer.tsx
  src/features/share/hooks/queries/useCardQuery.ts
  src/features/share/icons/DesignerIcon.tsx
  src/features/share/icons/DeveloperIcon.tsx
  src/features/share/mocks/index.ts
Labels: 🚀 feature

#131 [feat] 에러 핸들링 구현
  package.json
  pnpm-lock.yaml
  src/app/(detail)/card-detail/[cardId]/page.tsx
  src/app/api/auth/callback/[provider]/page.tsx
  src/features/card-detail/components/CardDetailSkelton.tsx
  src/features/card-detail/components/empty.tsx
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/ui/cardContent.tsx
  src/features/card-detail/ui/cardDetail.tsx
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/cardTabs.tsx
  src/middleware.ts
  src/shared/components/SSRSafeSuspense.tsx
  src/shared/providers/ApiErrorBoundary.tsx
  src/shared/providers/GlobalErrorBoundary.tsx
  src/shared/providers/QueryClientProvider.tsx
  src/shared/ui/error-boundary/ErrorFallback.tsx
  src/shared/ui/error-boundary/GlobalErrorFallback.tsx
  src/shared/ui/skeleton.tsx
  src/shared/utils/handleAxiosError.ts
Labels: 🚀 feature

#140 [feat] 명함 상세 페이지 API 연동
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/hooks/useScroll.ts
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/types/cardDetail.ts
  src/features/card-detail/ui/bottomSheet.tsx
  src/features/card-detail/ui/cardContent.tsx
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/cardTabs.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/bottomModal/bottomModal.tsx
  src/shared/ui/bottomModal/bottomModalItem.tsx
  src/shared/ui/bottomModal/bottomModalTitle.tsx
  src/shared/ui/bottomModal/memoInput.tsx
Labels: 🚀 feature

#143 [chore] update pnpm lock
  pnpm-lock.yaml
Labels: auto approve

#144 [Hotfix] disable api my fetching temporary
  src/features/home/hooks/queries/useCardQuery.ts
Labels: auto approve

#145 [hotfix] temporary disable react query hook - my/card
  src/features/home/hooks/queries/useCardQuery.ts
  src/features/share/hooks/queries/useCardQuery.ts
Labels: auto approve

#147 ♻️ refactor : 임시 데이터 설정 및 토스트 error svg 경로 수정
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/mocks/myCardDetail.ts
  src/shared/ui/Toast/index.tsx
Labels: auto approve, QA

#148 [feat] 명함 상세 페이지 QA
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/share/hooks/queries/useCardQuery.ts
  src/shared/ui/Toast/index.tsx
Labels: auto approve, QA
