Repository depromeet/Took-FE, pull requests merged in 2025-02, with the labels that each got.

#8 [chore] Deploy Vercel Workflow
  .github/workflows/deploy-integration.yml
  .github/workflows/deploy-target.yml
  .gitignore
Labels: auto approve

#9 [chore] Vercel Workflow 추가
  .github/workflows/deploy-integration.yml
  .github/workflows/deploy-target.yml
  .gitignore
Labels: auto approve

#10 [chore] Vercel Workflow 수정
  scripts/build.sh
Labels: auto approve

#11 [chore] Vercel Workflow 수정
  scripts/build.sh
Labels: auto approve

#12 [chore] Vercel Workflow 수정
  .github/workflows/deploy-integration.yml
Labels: auto approve

#13 [chore] Vercel Workflow 수정
  .github/workflows/deploy-integration.yml
Labels: auto approve

#6 [chore] Custom Local Dev Server
  .github/workflows/deploy-integration.yml
  README.md
  cspell.json
  package.json
  pnpm-lock.yaml
  scripts/build.sh
  scripts/https-local-server.js
  scripts/setup.sh
Labels: auto approve

#15 [chore] Custom Local Dev Server
  .github/workflows/deploy-integration.yml
  README.md
  cspell.json
  package.json
  pnpm-lock.yaml
  scripts/build.sh
  scripts/https-local-server.js
  scripts/setup.sh
Labels: auto approve

#19 [style]: 디자인 토큰 추가
  src/app/globals.css
  tailwind.config.ts
Labels: 💄 style

#25 [chore] PR Comment 슬랙 알림과 PR Reviewer 알림 추가
  .github/workflows/pr-comment.yml
  .github/workflows/pr-reivew.yml
Labels: ✅ Auto approve, 🏞️ env

#27 📦 chore: 모든 브랜치에 coderabbit ai 리뷰를 달게 합니다
  .coderabbit.yml
Labels: ✅ Auto approve, 🏞️ env

#30 📦️ Chore: shadcn/ui 설치
  components.json
  package.json
  src/lib/utils.ts
  tailwind.config.ts
Labels: 🏞️ env, 💄 style

#33 [Feat] 카카오 로그인 버튼 임시 구현
  pnpm-lock.yaml
  src/app/auth/[provider]/page.tsx
  src/app/login/page.tsx
  src/features/auth/model/index.ts
  src/features/auth/model/providers/kakao.ts
  src/features/auth/ui/KakaoLoginButton.tsx
  tailwind.config.ts
Labels: 🚀 feature

#36 [feature]: 타이포그라피 테일윈드 css 스타일 구현, 타이포그라피 컴포넌트 구현
  .husky/post-merge
  .husky/pre-push
  src/shared/ui/typography/index.tsx
  src/shared/ui/typography/typography.ts
  tailwind.config.ts
Labels: ✅ Auto approve, 🚀 feature, 💄 style
