Repository depromeet/Took-FE, pull requests merged in 2025-04, with the labels that each got.

#128 [feat] 알림 리스트 페이지 구현
  src/app/setting/alram-list/page.tsx
  src/app/setting/page.tsx
  src/features/setting/index.ts
  src/features/setting/ui/alarmList.tsx
  src/features/setting/ui/index.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/list/index.tsx
Labels: auto approve, 🚀 feature

#137 [Feat] 2차 MVP Home QR Code
  .eslintrc.js
  .husky/pre-push
  package.json
  pnpm-lock.yaml
  public/icons/logo.svg
  src/app/globals.css
  src/app/page.tsx
  src/app/share/page.tsx
  src/features/home/components/BusinessCard/Background/HomeBackground.tsx
  src/features/home/components/BusinessCard/Card.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/home/hooks/queries/useCardQuery.ts
  src/features/home/types/index.ts
  src/features/received/ui/receivedCard.tsx
  src/features/share/components/Background.tsx
  src/features/share/components/DecoAura.tsx
  src/features/share/components/JobLogo.tsx
  src/features/share/components/QrBackground.tsx
  src/features/share/components/QrInfo.tsx
  src/features/share/components/QrLogo.tsx
  src/features/share/components/ShareButton.tsx
  src/features/share/containers/BackgroundContainer.tsx
  src/features/share/containers/QrContainer.tsx
  src/features/share/containers/SegmentContainer.tsx
  src/shared/ui/Avatar/avatar.tsx
  src/shared/ui/Avatar/index.tsx
  src/shared/ui/Navigation/icons/MyCardIcon.tsx
  src/shared/ui/Navigation/icons/ReceivedCardIcon.tsx
  src/shared/ui/Navigation/icons/SettingIcon.tsx
  src/shared/ui/Navigation/index.tsx
Labels: auto approve, 🚀 feature, QA

#154 [fix] build error
  src/app/(create)/card-create/new-card/multi-step-form/page.tsx
  src/app/(received)/received/choose/page.tsx
  src/app/(received)/received/interesting/page.tsx
  src/features/received/ui/choose/chooseReceivedCardView.tsx
  src/features/received/ui/receivedCard.tsx
Labels: auto approve

#151 QA 1차 MVP
  src/features/card-create/config/index.ts
  src/features/multi-step-form/components/AvartarImg.tsx
  src/features/multi-step-form/hooks/queries/useCreateCard.ts
  src/features/multi-step-form/ui/careerForm/constants/index.ts
  src/features/multi-step-form/ui/careerForm/firstStep.tsx
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/careerForm/thridStep.tsx
  src/features/multi-step-form/utils/index.tsx
  src/features/setting/ui/alram.tsx
  src/middleware.ts
  src/shared/ui/Avatar/avatar.tsx
  src/shared/ui/dropDown/searchDropdown.tsx
  src/shared/ui/tagInput.tsx
  src/shared/ui/thumbnail.tsx
Labels: auto approve, 🚀 feature, QA

#155 카드생성 4.1 QA 적용 배포
  src/features/card-create/config/index.ts
  src/features/multi-step-form/components/AvartarImg.tsx
  src/features/multi-step-form/hooks/queries/useCreateCard.ts
  src/features/multi-step-form/ui/careerForm/constants/index.ts
  src/features/multi-step-form/ui/careerForm/firstStep.tsx
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/careerForm/thridStep.tsx
  src/features/multi-step-form/utils/index.tsx
  src/features/setting/ui/alram.tsx
  src/middleware.ts
  src/shared/ui/Avatar/avatar.tsx
  src/shared/ui/dropDown/searchDropdown.tsx
  src/shared/ui/tagInput.tsx
  src/shared/ui/thumbnail.tsx
Labels: auto approve

#156 [Fix] 명함 생성, 받은 명함 QA
  public/images/tag/background.png
  public/images/tag/background.webp
  src/features/multi-step-form/ui/careerForm/secondStep.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/Ball.tsx
  src/features/multi-step-form/ui/index.tsx
  src/features/received/ui/foldersList.tsx
  src/features/received/ui/receivedCard.tsx
  src/features/received/ui/receivedCardView.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/progressBar/progress.tsx
Labels: auto approve, QA

#159 [qa] 4/2 카드 생성 및 공통 컴포넌트
  src/shared/ui/Input/index.tsx
  src/shared/ui/Input/input.tsx
  src/shared/ui/tagInput.tsx
  src/shared/ui/textArea/index.tsx
Labels: auto approve, ♻️ refactor

#161 [feat] 동적 메타 태그 구현
  public/images/og/OG-01.png
  public/images/og/OG-02.png
  src/features/home/containers/CardContainer.tsx
  src/middleware.ts
  src/shared/components/seo/generateMetaData.tsx
  src/shared/constants/index.ts
Labels: auto approve

#163 🐛 HotFix: 로그인 isProd 플래그 수정
  src/features/auth/login/config/authConfig.ts
Labels: auto approve, 🐛 bug

#164 [feat] 메타 태그 적용
  src/app/layout.tsx
  src/features/auth/login/apis/getToken.ts
  src/features/auth/login/types/auth.ts
  src/features/multi-step-form/components/AvartarImg.tsx
  src/features/multi-step-form/config/index.ts
Labels: auto approve

#166 [feat] 명함 상세 페이지 QA 작업
  public/icons/imageIcon-gray.svg
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/ui/bottomSheet.tsx
  src/features/card-detail/ui/cardContent.tsx
  src/features/card-detail/ui/cardDetail.tsx
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/cardTabs.tsx
  src/features/card-detail/ui/domain.tsx
  src/features/card-detail/ui/hobby.tsx
  src/features/card-detail/ui/posts.tsx
  src/features/card-detail/ui/projects.tsx
  src/features/card-detail/ui/recent.tsx
  src/features/card-detail/ui/sns.tsx
  src/features/card-detail/ui/underlineTabs.tsx
  src/features/home/containers/CardContainer.tsx
  src/shared/providers/QueryClientProvider.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/bottomModal/bottomModal.tsx
  src/shared/ui/bottomModal/memoInput.tsx
  src/shared/ui/postThumbnail.tsx
Labels: auto approve, QA

#167 [feat] 명함 상세 페이지 QA 작업 (#166)
  public/icons/imageIcon-gray.svg
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/ui/bottomSheet.tsx
  src/features/card-detail/ui/cardContent.tsx
  src/features/card-detail/ui/cardDetail.tsx
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/cardTabs.tsx
  src/features/card-detail/ui/domain.tsx
  src/features/card-detail/ui/hobby.tsx
  src/features/card-detail/ui/posts.tsx
  src/features/card-detail/ui/projects.tsx
  src/features/card-detail/ui/recent.tsx
  src/features/card-detail/ui/sns.tsx
  src/features/card-detail/ui/underlineTabs.tsx
  src/features/home/containers/CardContainer.tsx
  src/shared/providers/QueryClientProvider.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/bottomModal/bottomModal.tsx
  src/shared/ui/bottomModal/memoInput.tsx
  src/shared/ui/postThumbnail.tsx
Labels: auto approve, QA

#171 [feat] 명함 상세 페이지 2차 QA 작업
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/ui/cardTabs.tsx
  src/features/card-detail/ui/sns.tsx
  src/features/card-detail/utils/filteredTabs.ts
  src/shared/ui/bottomModal/memoInput.tsx
Labels: auto approve, QA

#172 [feat] 명함 상세 페이지 QA 작업
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/ui/cardTabs.tsx
  src/features/card-detail/ui/sns.tsx
  src/features/card-detail/utils/filteredTabs.ts
  src/shared/ui/bottomModal/memoInput.tsx
Labels: auto approve, QA

#175 [develop] home refactor detail, share page
  src/app/globals.css
  src/app/share/page.tsx
  src/features/card-detail/config/jobs-config.ts
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/onboarding/config/slides.tsx
  src/features/share/containers/QrContainer.tsx
Labels: auto approve

#176 [main] home refactor detail, share page
  src/app/globals.css
  src/app/share/page.tsx
  src/features/card-detail/config/jobs-config.ts
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/onboarding/config/slides.tsx
  src/features/share/containers/QrContainer.tsx
Labels: auto approve

#177 refactor: silde align center
  src/features/home/containers/CardContainer.tsx
Labels: auto approve

#178 [Fix] 명함 생성, 받은 명함 QA 2차
  next.config.mjs
  src/app/(received)/received/choose/page.tsx
  src/app/(received)/received/page.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/TagBox.tsx
  src/features/received/ui/emptyCard.tsx
  src/features/received/ui/foldersList.tsx
  src/features/received/ui/intellibanner.tsx
  src/features/received/ui/lottieLoading.tsx
  src/features/received/ui/receivedCard.tsx
  src/features/received/ui/receivedCardView.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/thumbnail.tsx
Labels: auto approve, QA

#179 [fix] 카드 생성 url 파싱, 편집 카드 title 수정 프론트 위임
  src/features/multi-step-form/components/EditableCardField.tsx
  src/features/multi-step-form/utils/index.tsx
Labels: auto approve

#180 [fix]4/3 카드 생성 QA
  src/features/multi-step-form/components/EditableCardField.tsx
  src/features/multi-step-form/utils/index.tsx
Labels: auto approve

#173 [feat] 명함 상세 페이지 2차 QA 작업 수정
  next.config.mjs
  src/features/card-detail/config/jobs-config.ts
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/types/cardDetail.ts
  src/features/card-detail/ui/cardDetail.tsx
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/projects.tsx
  src/features/received/ui/lottieLoading.tsx
  src/shared/ui/bottomModal/memoInput.tsx
Labels: auto approve, QA

#181 [feat] 명함 상세 페이지 2차 QA 작업 수정
  next.config.mjs
  src/features/card-detail/config/jobs-config.ts
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/types/cardDetail.ts
  src/features/card-detail/ui/cardDetail.tsx
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/projects.tsx
  src/features/received/ui/lottieLoading.tsx
  src/shared/ui/bottomModal/memoInput.tsx
Labels: auto approve, QA

#183 [feat] Job 타입 수정
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/home/components/BusinessCard/Card.tsx
  src/features/home/components/BusinessCard/CardTag.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/home/types/index.ts
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/received/ui/receivedCard.tsx
  src/features/share/components/Background.tsx
  src/features/share/components/JobLogo.tsx
  src/features/share/components/QrInfo.tsx
  src/features/share/components/ShareButton.tsx
  src/features/share/components/ShareCard.tsx
  src/features/share/components/ShareCardTag.tsx
  src/features/share/containers/BackgroundContainer.tsx
  src/features/share/containers/QrContainer.tsx
Labels: auto approve, 🐛 bug

#184 [feat] Job 타입 수정
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/home/components/BusinessCard/Card.tsx
  src/features/home/components/BusinessCard/CardTag.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/home/types/index.ts
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/received/ui/receivedCard.tsx
  src/features/share/components/Background.tsx
  src/features/share/components/JobLogo.tsx
  src/features/share/components/QrInfo.tsx
  src/features/share/components/ShareButton.tsx
  src/features/share/components/ShareCard.tsx
  src/features/share/components/ShareCardTag.tsx
  src/features/share/containers/BackgroundContainer.tsx
  src/features/share/containers/QrContainer.tsx
Labels: auto approve, 🐛 bug

#185 [feat] 회원 로그아웃 구현
  src/features/setting/hooks/useLogout.ts
  src/features/setting/ui/index.tsx
  src/shared/components/seo/generateMetaData.tsx
  src/shared/hooks/useCookies.ts
  src/shared/ui/dialog/wrappedDialog.tsx
  src/shared/utils/cookies.ts
  src/shared/utils/handleAxiosError.ts
  src/shared/utils/sleep.ts
Labels: auto approve, 🚀 feature, ♻️ refactor

#186 회원 탈퇴
  src/features/card-create/ui/onBoardingView.tsx
  src/features/setting/hooks/useWithdraw.ts
  src/features/setting/schema/index.ts
  src/features/setting/ui/dialog/withdraw.tsx
  src/features/setting/ui/index.tsx
  src/features/setting/ui/userQuit.tsx
  src/shared/ui/Navigation/index.tsx
  src/shared/ui/button/fixedButton.tsx
Labels: auto approve, 🚀 feature

#187 💄 Style: 로그인 페이지 고정 이미지 가변적으로 수정
  src/features/auth/login/ui/LoginFeature.tsx
  src/features/login/components/Background.tsx
  src/features/login/containers/LoginBackgroundContainer.tsx
Labels: auto approve, QA

#188 merge: 회원 탈퇴, 로그아웃, 로그인 컨테이너 스타일 수정
  src/features/auth/login/ui/LoginFeature.tsx
  src/features/card-create/ui/onBoardingView.tsx
  src/features/login/components/Background.tsx
  src/features/login/containers/LoginBackgroundContainer.tsx
  src/features/setting/hooks/useLogout.ts
  src/features/setting/hooks/useWithdraw.ts
  src/features/setting/schema/index.ts
  src/features/setting/ui/dialog/withdraw.tsx
  src/features/setting/ui/index.tsx
  src/features/setting/ui/userQuit.tsx
  src/shared/components/seo/generateMetaData.tsx
  src/shared/hooks/useCookies.ts
  src/shared/ui/Navigation/index.tsx
  src/shared/ui/button/fixedButton.tsx
  src/shared/ui/dialog/wrappedDialog.tsx
  src/shared/utils/cookies.ts
  src/shared/utils/handleAxiosError.ts
  src/shared/utils/sleep.ts
Labels: auto approve, 🚀 feature, ♻️ refactor, QA

#189 [QA] 받은 명함 QA 2차
  src/features/received/config/index.ts
  src/features/received/model/useModal.ts
  src/features/received/ui/choose/chooseReceivedCardView.tsx
  src/features/received/ui/foldersList.tsx
  src/features/received/ui/receivedCardList.tsx
  src/features/received/ui/receivedCardView.tsx
  src/features/received/ui/sortModal.tsx
  src/shared/ui/lottieLoading.tsx
Labels: auto approve, QA

#190 ✨ Feat: 앱바 고정을 위해 프로그레스바 옵션 추가, 앱바 스타일 수정
  src/features/multi-step-form/ui/index.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/progressBar/index.tsx
Labels: auto approve, 💄 style

#191 [feat] 명함 공유 저장 페이지 구현
  next.config.mjs
  src/app/(share)/card-share/[id]/page.tsx
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/hooks/useBottomModal.ts
  src/features/card-detail/ui/cardDetail.tsx
  src/features/onboarding/screen/index.tsx
  src/features/share/components/ShareCard.tsx
  src/features/share/container/AnimatedShareCardWrapper.tsx
  src/features/share/container/OpenShareCardDetailContainer.tsx
  src/features/share/container/ShareCardContentContainer.tsx
  src/features/share/container/ShareClipboardContainer.tsx
  src/features/share/hooks/mutations/useSaveCard.ts
  src/features/share/hooks/queries/useCardQuery.ts
  src/features/share/mocks/index.ts
  src/features/share/store/shareStore.ts
  src/features/share/types/index.ts
  src/middleware.ts
  src/shared/hooks/useHistoryBack.ts
  src/shared/hooks/useIsLoggedIn.ts
  src/shared/utils/handleAxiosError.ts
Labels: auto approve, 🚀 feature

#192 [feat] 명함 공유 저장 페이지 구현
  next.config.mjs
  src/app/(share)/card-share/[id]/page.tsx
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/hooks/useBottomModal.ts
  src/features/card-detail/ui/cardDetail.tsx
  src/features/multi-step-form/ui/index.tsx
  src/features/onboarding/screen/index.tsx
  src/features/share/components/ShareCard.tsx
  src/features/share/container/AnimatedShareCardWrapper.tsx
  src/features/share/container/OpenShareCardDetailContainer.tsx
  src/features/share/container/ShareCardContentContainer.tsx
  src/features/share/container/ShareClipboardContainer.tsx
  src/features/share/hooks/mutations/useSaveCard.ts
  src/features/share/hooks/queries/useCardQuery.ts
  src/features/share/mocks/index.ts
  src/features/share/store/shareStore.ts
  src/features/share/types/index.ts
  src/middleware.ts
  src/shared/hooks/useHistoryBack.ts
  src/shared/hooks/useIsLoggedIn.ts
  src/shared/ui/appbar.tsx
  src/shared/ui/progressBar/index.tsx
  src/shared/utils/handleAxiosError.ts
Labels: auto approve, 🚀 feature

#195 [release] 외부 이미지 도메인 허용
  next.config.mjs
Labels: auto approve, 🐛 bug, QA

#196 [hotfix] 카드 생성 SNS TYPE 전달 수정
  src/features/multi-step-form/components/EditableCardField.tsx
  src/features/multi-step-form/config/index.ts
  src/features/multi-step-form/ui/careerForm/firstStep.tsx
  src/features/multi-step-form/ui/index.tsx
Labels: auto approve, 🚀 feature

#197 [hotfix] 카드 생성 수정
  src/features/multi-step-form/components/EditableCardField.tsx
  src/features/multi-step-form/config/index.ts
  src/features/multi-step-form/ui/careerForm/firstStep.tsx
  src/features/multi-step-form/ui/index.tsx
Labels: auto approve

#198 [fix] 4/5 QA
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/index.tsx
  src/features/setting/ui/userQuit.tsx
Labels: auto approve, QA

#199 4/5 QA
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/index.tsx
  src/features/setting/ui/userQuit.tsx
  src/shared/ui/thumbnail.tsx
Labels: auto approve

#200 🐛 Fix: 선택 태그 로컬 화 zustand shallow 로컬화해서 재처리
  src/features/multi-step-form/ui/careerForm/thridStep.tsx
Labels: auto approve, ♻️ refactor, QA

#209 [Feat] 받은 명함 QA 3차
  src/features/home/types/index.ts
  src/features/multi-step-form/ui/careerForm/tagFormStep/config/config.ts
  src/features/multi-step-form/ui/index.tsx
  src/features/received/ui/foldersList.tsx
  src/features/received/ui/receivedCard.tsx
  src/features/received/ui/receivedCardView.tsx
  src/features/received/ui/sortModal.tsx
  src/shared/ui/header.tsx
  src/shared/ui/progressBar/progress.tsx
  src/shared/ui/thumbnail.tsx
  tailwind.config.ts
Labels: auto approve, QA

#211 Merge develop to main
  src/features/home/types/index.ts
  src/features/multi-step-form/ui/careerForm/tagFormStep/config/config.ts
  src/features/multi-step-form/ui/index.tsx
  src/features/received/ui/foldersList.tsx
  src/features/received/ui/receivedCard.tsx
  src/features/received/ui/receivedCardView.tsx
  src/features/received/ui/sortModal.tsx
  src/shared/ui/header.tsx
  src/shared/ui/progressBar/progress.tsx
  src/shared/ui/thumbnail.tsx
  tailwind.config.ts
Labels: auto approve

#212 Hotfix/thumbnail
  src/features/received/ui/receivedCard.tsx
  src/shared/ui/img.tsx
Labels: auto approve

#213 Merge develop to main
  src/features/received/ui/receivedCard.tsx
  src/shared/ui/img.tsx
Labels: auto approve

#215 [feat] 명함 공유 저장 페이지 , 상세 페이지 QA 작업
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/ui/bottomSheet.tsx
  src/features/card-detail/ui/cardDetail.tsx
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/cardTabs.tsx
  src/features/share/components/ShareCard.tsx
  src/features/share/container/AnimatedShareCardWrapper.tsx
  src/features/share/container/ShareCardContentContainer.tsx
  src/features/share/mocks/index.ts
  src/shared/ui/postThumbnail.tsx
Labels: auto approve, QA

#216 [feat] 명함 공유 저장 페이지 , 상세 페이지 QA 작업
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/ui/bottomSheet.tsx
  src/features/card-detail/ui/cardDetail.tsx
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/cardTabs.tsx
  src/features/share/components/ShareCard.tsx
  src/features/share/container/AnimatedShareCardWrapper.tsx
  src/features/share/container/ShareCardContentContainer.tsx
  src/features/share/mocks/index.ts
  src/shared/ui/postThumbnail.tsx
Labels: auto approve, QA

#217 [refactor] 작성한 글 텍스트 길이 수정
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/ui/projects.tsx
  src/shared/ui/postThumbnail.tsx
Labels: auto approve, QA

#218 [refactor] 작성한 글 텍스트 길이 수정
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/ui/projects.tsx
  src/shared/ui/postThumbnail.tsx
Labels: auto approve, QA

#220 Hotfix/thumbnail 2
  src/app/share/page.tsx
  src/features/home/containers/ClipboardContainer.tsx
Labels: auto approve

#222 [refactor] 홈 화면 수정
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/ui/projects.tsx
  src/features/home/components/BusinessCard/Card.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/share/components/ShareCard.tsx
  src/features/share/container/ShareCardContentContainer.tsx
  src/shared/ui/img.tsx
  src/shared/ui/postThumbnail.tsx
Labels: auto approve, QA

#223 [refactor] 홈 화면 수정
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/ui/projects.tsx
  src/features/home/components/BusinessCard/Card.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/share/components/ShareCard.tsx
  src/features/share/container/ShareCardContentContainer.tsx
  src/shared/ui/img.tsx
  src/shared/ui/postThumbnail.tsx
Labels: auto approve, QA

#226 [fix] 토스터 중복 수정
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/shared/ui/lottieLoading.tsx
Labels: auto approve, QA

#227 배포
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/shared/ui/lottieLoading.tsx
Labels: auto approve, QA

#228 refactor : 작성한 글 , 대표 프로젝트 placeholder 수정
  src/features/multi-step-form/ui/careerForm/thridStep.tsx
Labels: auto approve

#229 refactor : 작성한 글 , 대표 프로젝트 placeholder 수정
  src/features/multi-step-form/ui/careerForm/thridStep.tsx
Labels: auto approve

#234 [feat] 명함 공유 로직 분리 및 토스트 위치 수정
  src/app/(received)/received/page.tsx
  src/features/card-detail/hooks/useScroll.ts
  src/features/card-detail/ui/cardDetail.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/share/container/ShareCardContentContainer.tsx
  src/features/share/utils/convertPreviewType.ts
  src/features/share/utils/getPreviewContent.ts
  src/shared/ui/Toast/index.ts
  src/shared/ui/Toast/index.tsx
  src/shared/ui/Toast/sonner.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/bottomModal/memoInput.tsx
Labels: auto approve, ♻️ refactor

#236 ✨ Feat: 폴더 이름 설정, 폴더 추가 바텀 시트에 버튼 추가
  src/features/received/ui/receivedCardView.tsx
  src/shared/ui/appbar.tsx
Labels: auto approve, QA

#237 [feat] 명함 삭제 모달 구현
  src/features/card-detail/ui/bottomSheet.tsx
  src/features/received/ui/choose/chooseReceivedCardView.tsx
  src/shared/ui/Toast/index.tsx
  src/shared/ui/Toast/sonner.tsx
  src/shared/ui/Toast/types/index.ts
Labels: auto approve, 🚀 feature

#240 [feat] 카드 생성 - 웹뷰 지원 구현
  src/features/auth/login/utils/nativeBridge.ts
  src/features/multi-step-form/components/AvartarImg.tsx
Labels: auto approve, 🚀 feature

#241 [deploy] 웹뷰 카드 생성을 위한 배포
  src/app/(received)/received/page.tsx
  src/features/auth/login/utils/nativeBridge.ts
  src/features/card-detail/hooks/useScroll.ts
  src/features/card-detail/ui/bottomSheet.tsx
  src/features/card-detail/ui/cardDetail.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/multi-step-form/components/AvartarImg.tsx
  src/features/received/ui/choose/chooseReceivedCardView.tsx
  src/features/received/ui/receivedCardView.tsx
  src/features/share/container/ShareCardContentContainer.tsx
  src/features/share/utils/convertPreviewType.ts
  src/features/share/utils/getPreviewContent.ts
  src/shared/ui/Toast/index.tsx
  src/shared/ui/Toast/sonner.tsx
  src/shared/ui/Toast/types/index.ts
  src/shared/ui/appbar.tsx
  src/shared/ui/bottomModal/memoInput.tsx
Labels: auto approve, 🚀 feature, QA

#245 ✨ Feat: 카메라 브릿지, 드롭다운 추가
  src/features/multi-step-form/components/AvartarImg.tsx
Labels: auto approve, 🚀 feature

#246 [deploy] 앱 카메라 브릿지 및 드롭다운 적용
  src/features/multi-step-form/components/AvartarImg.tsx
Labels: auto approve, 🚀 feature

#247 🐛 Fix: 이미지 피커 및 카메라 브릿지 함수 두 번 호출 수정
  src/features/multi-step-form/components/AvartarImg.tsx
Labels: auto approve, 🐛 bug, ♻️ refactor

#136 [refactor] 애플 로그인
  src/app/api/auth/callback/[provider]/page.tsx
  src/app/api/auth/callback/apple/route.ts
Labels: auto approve

#248 애플로그인 배포
  src/app/api/auth/callback/[provider]/page.tsx
  src/app/api/auth/callback/apple/route.ts
Labels: auto approve

#243 [Refactor] 받은 명함 페이지 - 폴더 기능 리팩토링
  src/features/received/config/index.ts
  src/features/received/model/useAddFolderModal.ts
  src/features/received/model/useDeleteFolderModal.ts
  src/features/received/model/useUpdateFolderModal.ts
  src/features/received/ui/receivedCardView.tsx
Labels: auto approve, ♻️ refactor, QA

#249 [Fix] 버튼 클릭해도 폴더 추가, 수정 안되는 오류 수정
  src/features/received/model/useAddFolderModal.ts
  src/features/received/model/useUpdateFolderModal.ts
  src/features/received/ui/receivedCardView.tsx
  src/shared/ui/Toast/sonner.tsx
Labels: auto approve

#251 [deploy] 개인정보처리 약관, 이용약관 퍼블릭 URL 수정. 폴더 생성 도메인 개선
  src/features/auth/login/ui/LoginButton.tsx
  src/features/received/config/index.ts
  src/features/received/model/useAddFolderModal.ts
  src/features/received/model/useDeleteFolderModal.ts
  src/features/received/model/useUpdateFolderModal.ts
  src/features/received/ui/receivedCardView.tsx
  src/middleware.ts
  src/shared/ui/Toast/sonner.tsx
Labels: auto approve, 🚀 feature, ♻️ refactor, QA

#242 [feat] 에러 바운드리 구현 및 토스트 수정
  public/icons/error.svg
  src/app/(detail)/card-detail/[cardId]/page.tsx
  src/features/card-detail/hooks/mutation/useCardDeleteMutation.ts
  src/features/card-detail/hooks/mutation/useMemoMutation.ts
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/ui/bottomSheet.tsx
  src/middleware.ts
  src/shared/providers/ApiErrorBoundary.tsx
  src/shared/providers/GlobalErrorBoundary.tsx
  src/shared/providers/QueryClientProvider.tsx
  src/shared/providers/index.tsx
  src/shared/ui/Toast/sonner.tsx
  src/shared/ui/bottomModal/memoInput.tsx
  src/shared/ui/error-boundary/ErrorFallback.tsx
  src/shared/ui/error-boundary/ErrorHandlingWrapper.tsx
  src/shared/ui/error-boundary/GlobalErrorFallback.tsx
  src/shared/ui/error-boundary/errorConfig.ts
Labels: 🚀 feature

#254 refactor : 에러 바운드리 파일명 임시 수정
  src/app/(detail)/card-detail/[cardId]/page.tsx
  src/shared/providers/ApiErrorBoundary.tsx
  src/shared/providers/GlobalErrorBoundary.tsx
Labels: auto approve, ♻️ refactor

#255 [feat] 흥미로운 명함 스타일 수정 및 라우팅 추가
  public/icons/leftArrow-gray.svg
  src/app/(received)/received/interesting/page.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/error-boundary/GlobalErrorFallback.tsx
Labels: auto approve, ♻️ refactor

#257 [refactor] apple login 정상화
  src/features/auth/login/ui/LoginButton.tsx
Labels: auto approve

#258 [main] 애플로그인 및 에러바운더리 배포
  public/icons/error.svg
  public/icons/leftArrow-gray.svg
  src/app/(detail)/card-detail/[cardId]/page.tsx
  src/app/(received)/received/interesting/page.tsx
  src/features/auth/login/ui/LoginButton.tsx
  src/features/card-detail/hooks/mutation/useCardDeleteMutation.ts
  src/features/card-detail/hooks/mutation/useMemoMutation.ts
  src/features/card-detail/hooks/query/useCardDetailQuery.ts
  src/features/card-detail/ui/bottomSheet.tsx
  src/middleware.ts
  src/shared/providers/QueryClientProvider.tsx
  src/shared/providers/index.tsx
  src/shared/ui/Toast/sonner.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/bottomModal/memoInput.tsx
  src/shared/ui/error-boundary/ErrorFallback.tsx
  src/shared/ui/error-boundary/ErrorHandlingWrapper.tsx
  src/shared/ui/error-boundary/GlobalErrorFallback.tsx
  src/shared/ui/error-boundary/errorConfig.ts
Labels: auto approve

#259 [main] fix import error
  src/app/(detail)/card-detail/[cardId]/page.tsx
Labels: auto approve

#260 [Feat] 공유 스와이프 인터랙션 및 스와이프 시 공유 화면으로 라우팅
  src/features/home/containers/CardContainer.tsx
  tailwind.config.ts
Labels: auto approve

#261 [fix] 구글 로그인 브릿지 코드 수정
  src/features/auth/login/ui/LoginButton.tsx
  src/features/auth/login/utils/nativeBridge.ts
  src/middleware.ts
Labels: auto approve

#262 [deploy] 구글 브릿지 코드 수정 배포, 공유 스와이프 로직 추가
  src/features/auth/login/ui/LoginButton.tsx
  src/features/auth/login/utils/nativeBridge.ts
  src/features/home/containers/CardContainer.tsx
  src/middleware.ts
  tailwind.config.ts
Labels: auto approve

#263 ✏️ Fix: 브릿지 코드 테스트
  src/features/auth/login/ui/LoginButton.tsx
  src/features/auth/login/utils/nativeBridge.ts
Labels: auto approve

#264 [deploy] 브릿지 코드 테스트
  src/features/auth/login/ui/LoginButton.tsx
  src/features/auth/login/utils/nativeBridge.ts
Labels: auto approve

#265 [Refactor] 명함 생성 - 태그 선택 애니메이션 framer-motion 사용 리팩토링
  src/features/multi-step-form/ui/careerForm/secondStep.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/config/config.ts
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/TmpTagBox.tsx
Labels: auto approve, ♻️ refactor

#267 Merge develop to main
  src/features/multi-step-form/ui/careerForm/secondStep.tsx
  src/features/multi-step-form/ui/careerForm/tagFormStep/config/config.ts
  src/features/multi-step-form/ui/careerForm/tagFormStep/ui/TmpTagBox.tsx
Labels: auto approve

#269 [feat] 대표 명함 기능 추가
  src/app/(detail)/card-detail/[cardId]/page.tsx
  src/features/card-detail/config/sns-config.ts
  src/features/card-detail/hooks/mutation/useCardPrimaryMutation.ts
  src/features/card-detail/hooks/query/useCardQuery.ts
  src/features/card-detail/mocks/myCardDetail.ts
  src/features/card-detail/types/cardDetail.ts
  src/features/card-detail/types/myCard.ts
  src/features/card-detail/ui/bottomSheet.tsx
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/cardTabs.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/home/types/index.ts
  src/features/share/types/index.ts
Labels: auto approve, 🚀 feature

#273 [feat] 흥미로운 명함 API 연동 완료
  src/app/(received)/received/interesting/page.tsx
  src/features/received/model/queries/useInterestCardsQuery.ts
  src/features/received/types/interestCards.ts
  src/features/received/ui/receivedCard.tsx
  src/features/received/ui/receivedCardView.tsx
Labels: auto approve, 🚀 feature

#274 🐛 Fix: 구글 로그인 방식 수정
  src/features/auth/login/ui/LoginButton.tsx
  src/features/auth/login/utils/nativeBridge.ts
Labels: auto approve

#276 🐛 Hotfix: 파일 참조 에러 수정
  src/app/(detail)/card-detail/[cardId]/page.tsx
Labels: auto approve

#277 ♻️ Refactor: 개인정보처리 방침, 회원탈퇴, 이용약관을 공개 주소로 수정합니다.
  src/middleware.ts
Labels: auto approve

#279 Merge develop to main
  public/icons/clockIcon.svg
  public/icons/searchIcon-white.svg
  src/app/(received)/received/page.tsx
  src/app/(received)/received/search/page.tsx
  src/features/received/config/index.ts
  src/features/received/ui/choose/chooseReceivedCardView.tsx
  src/features/received/ui/receivedCard.tsx
  src/features/received/ui/receivedCardList.tsx
  src/features/received/ui/search/latestSearchKeyword.tsx
  src/features/received/ui/search/searchCardView.tsx
  src/shared/lib/highlightText.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/tag/tag.tsx
  src/shared/ui/thumbnail.tsx
Labels: auto approve

#280 [feat] 명함 공유 페이지 브릿지 및 딥링크 구현
  src/features/auth/login/utils/nativeBridge.ts
  src/features/share/container/AnimatedShareCardWrapper.tsx
  src/middleware.ts
Labels: auto approve, 🚀 feature

#283 [feat] useDevice 훅 모바일 기기 감지 하기위해 확장, 모바일 환경 딥링크 적용
  src/features/share/container/AnimatedShareCardWrapper.tsx
  src/shared/hooks/useDevice.ts
Labels: auto approve

#284 [deploy] 카드 공유 - 모바일 환경 딥링크 적용
  src/features/share/container/AnimatedShareCardWrapper.tsx
  src/shared/hooks/useDevice.ts
Labels: auto approve

#285 [Fix] 받은 명함 검색 오류 수정, 아래 스와이프 구현
  src/app/(received)/received/choose/page.tsx
  src/app/(received)/received/search/page.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/received/ui/search/latestSearchKeyword.tsx
  src/features/share/containers/QrContainer.tsx
Labels: auto approve, 🐛 bug, QA

#286 [feat]딥링크 후 저장 로직 및 라우팅 수정, 소셜 로그인 웹뷰 브릿지 코드 적용
  src/features/auth/login/apis/getToken.ts
  src/features/auth/login/utils/nativeBridge.ts
  src/features/share/container/AnimatedShareCardWrapper.tsx
  src/shared/hooks/useDevice.ts
Labels: auto approve

#287 [deploy] 명함 아래 스와이프 구현, 소셜로그인 브릿지 코드 추가, 카드 생성 딥링크 로직 수정
  src/app/(received)/received/choose/page.tsx
  src/app/(received)/received/search/page.tsx
  src/features/auth/login/apis/getToken.ts
  src/features/auth/login/utils/nativeBridge.ts
  src/features/home/containers/CardContainer.tsx
  src/features/received/ui/search/latestSearchKeyword.tsx
  src/features/share/container/AnimatedShareCardWrapper.tsx
  src/features/share/containers/QrContainer.tsx
  src/shared/hooks/useDevice.ts
Labels: auto approve

#288 [feat] 카드 공유 페이지 - 관심사 분리 훅 적용 및 딥링크 조건 개선
  src/features/share/container/AnimatedShareCardWrapper.tsx
  src/features/share/hooks/mutations/useSaveCard.ts
  src/features/share/hooks/useCardDetail.ts
  src/features/share/hooks/useCardShareAutoAction.ts
  src/middleware.ts
Labels: auto approve, 🚀 feature

#289 [deploy] 카드 공유 - 딥링크 개선 및 로직 관심사 분리 적용
  src/features/share/container/AnimatedShareCardWrapper.tsx
  src/features/share/hooks/mutations/useSaveCard.ts
  src/features/share/hooks/useCardDetail.ts
  src/features/share/hooks/useCardShareAutoAction.ts
  src/middleware.ts
Labels: auto approve

#278 [feat] 한 줄 메모 명함 리스트 구현
  public/icons/check.svg
  src/app/(detail)/card-detail/[cardId]/page.tsx
  src/app/(notes)/card-notes/memo/page.tsx
  src/app/(notes)/card-notes/page.tsx
  src/app/globals.css
  src/features/card-notes/components/Card.tsx
  src/features/card-notes/components/CardTag.tsx
  src/features/card-notes/hooks/mutation/useCardMemosMutation.ts
  src/features/card-notes/hooks/queries/useCardQuery.ts
  src/features/card-notes/hooks/useSelectCard.ts
  src/features/card-notes/mocks/index.ts
  src/features/card-notes/store/selectCardStore.ts
  src/features/card-notes/types/index.ts
  src/features/card-notes/ui/memo/cardNotesMemo.tsx
  src/features/card-notes/ui/memo/cardNotesMemoCard.tsx
  src/features/card-notes/ui/memo/cardNotesMemoHeader.tsx
  src/features/card-notes/ui/memo/cardNotesMemoMain.tsx
  src/features/card-notes/ui/select/cardNotes.tsx
  src/features/card-notes/ui/select/cardNotesCard.tsx
  src/features/card-notes/ui/select/cardNotesHeader.tsx
  src/features/card-notes/ui/select/cardNotesMain.tsx
  src/features/card-notes/utils/convertPreviewType.ts
  src/features/card-notes/utils/getPreviewContent.ts
  src/features/received/ui/emptyCard.tsx
  src/shared/ui/appbar.tsx
  src/shared/ui/error-boundary/GlobalErrorFallback.tsx
Labels: auto approve, 🚀 feature

#292 [deploy] 한줄 메모 도메인 구현, 알림 웹뷰 브릿지 구현
  public/icons/check.svg
  src/app/(notes)/card-notes/memo/page.tsx
  src/app/(notes)/card-notes/page.tsx
  src/app/globals.css
  src/features/auth/login/apis/getToken.ts
  src/features/card-notes/components/Card.tsx
  src/features/card-notes/components/CardTag.tsx
  src/features/card-notes/hooks/mutation/useCardMemosMutation.ts
  src/features/card-notes/hooks/queries/useCardQuery.ts
  src/features/card-notes/hooks/useSelectCard.ts
  src/features/card-notes/mocks/index.ts
  src/features/card-notes/store/selectCardStore.ts
  src/features/card-notes/types/index.ts
  src/features/card-notes/ui/memo/cardNotesMemo.tsx
  src/features/card-notes/ui/memo/cardNotesMemoCard.tsx
  src/features/card-notes/ui/memo/cardNotesMemoHeader.tsx
  src/features/card-notes/ui/memo/cardNotesMemoMain.tsx
  src/features/card-notes/ui/select/cardNotes.tsx
  src/features/card-notes/ui/select/cardNotesCard.tsx
  src/features/card-notes/ui/select/cardNotesHeader.tsx
  src/features/card-notes/ui/select/cardNotesMain.tsx
  src/features/card-notes/utils/convertPreviewType.ts
  src/features/card-notes/utils/getPreviewContent.ts
  src/features/multi-step-form/components/AvartarImg.tsx
  src/features/onboarding/screen/index.tsx
  src/features/received/ui/emptyCard.tsx
  src/shared/hooks/usePushToken.ts
  src/shared/lib/utils.ts
  src/shared/ui/appbar.tsx
  src/shared/ui/error-boundary/GlobalErrorFallback.tsx
  src/shared/utils/nativeBridge.ts
  src/store/pushTokenStore.ts
  src/types/global.d.ts
Labels: auto approve, 🚀 feature

#294 [deploy] 로그인 시 expo 푸시알림 토큰 전달
  src/features/auth/login/apis/getToken.ts
  src/features/auth/login/types/auth.ts
  src/features/onboarding/screen/index.tsx
Labels: auto approve, 🚀 feature

#295 [fix] 로그인 웹뷰 푸시 토큰 파싱 로직 추가 및 로그인 요청 페이로드 수정
  src/features/auth/login/apis/getToken.ts
  src/features/auth/login/types/auth.ts
Labels: auto approve, 🚀 feature

#298 [feat] 알림 설정 웹뷰 브릿지 코드 추가, 알림 설정 리스트 API 연동 및 구현 완료
  package.json
  pnpm-lock.yaml
  src/features/auth/login/apis/getToken.ts
  src/features/setting/constants/index.ts
  src/features/setting/hooks/useGetNotification.ts
  src/features/setting/hooks/useGetNotificationAllow.ts
  src/features/setting/hooks/useGetNotificationList.ts
  src/features/setting/hooks/useNotificationSettings.ts
  src/features/setting/hooks/usePatchNotificationAllow.ts
  src/features/setting/mock/index.ts
  src/features/setting/ui/alarmList.tsx
  src/features/setting/ui/alram.tsx
  src/features/setting/ui/index.tsx
  src/features/setting/utils/index.ts
  src/middleware.ts
  src/shared/apis/client.ts
  src/shared/hooks/useDevice.ts
  src/shared/hooks/useWebview.ts
  src/shared/hooks/useWindowSize.ts
  src/shared/utils/nativeBridge.ts
Labels: auto approve, 🚀 feature

#299 [deploy] 알림 도메인 구현
  package.json
  pnpm-lock.yaml
  src/features/auth/login/apis/getToken.ts
  src/features/setting/constants/index.ts
  src/features/setting/hooks/useGetNotification.ts
  src/features/setting/hooks/useGetNotificationAllow.ts
  src/features/setting/hooks/useGetNotificationList.ts
  src/features/setting/hooks/useNotificationSettings.ts
  src/features/setting/hooks/usePatchNotificationAllow.ts
  src/features/setting/mock/index.ts
  src/features/setting/ui/alarmList.tsx
  src/features/setting/ui/alram.tsx
  src/features/setting/ui/index.tsx
  src/features/setting/utils/index.ts
  src/middleware.ts
  src/shared/apis/client.ts
  src/shared/hooks/useDevice.ts
  src/shared/hooks/useWebview.ts
  src/shared/hooks/useWindowSize.ts
  src/shared/utils/nativeBridge.ts
Labels: auto approve

#300 ✨ Feat: 문의사항 페이지 웹뷰 브릿지 추가
  src/features/setting/ui/index.tsx
  src/shared/utils/nativeBridge.ts
Labels: auto approve, 🚀 feature

#301 [deploy] 알림 설정 최신값으로 전달 수정 및 배포
  src/features/setting/hooks/useNotificationSettings.ts
Labels: auto approve, 🐛 bug

#302 🐛 Fix: 카드 공유 딥링크 개선
  src/features/share/hooks/useCardShareAutoAction.ts
Labels: auto approve

#296 [feat] 명함 수정 구현 진행중
  src/features/card-create/ui/onBoardingView.tsx
  src/features/card-detail/store/updateCardStore.ts
  src/features/card-detail/ui/bottomSheet.tsx
  src/features/card-detail/ui/cardDetail.tsx
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/multi-step-form/components/AvartarImg.tsx
  src/features/multi-step-form/config/index.ts
  src/features/multi-step-form/hooks/queries/useUpdateCard.ts
  src/features/multi-step-form/hooks/queries/useUpdateCardInfo.ts
  src/features/multi-step-form/schema/index.ts
  src/features/multi-step-form/types/index.ts
  src/features/multi-step-form/ui/careerForm/firstStep.tsx
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/utils/index.tsx
Labels: auto approve, 🐛 bug, 🚀 feature

#305 [feat] 명함 수정 구현 진행중
  src/features/card-create/ui/onBoardingView.tsx
  src/features/card-detail/store/updateCardStore.ts
  src/features/card-detail/ui/bottomSheet.tsx
  src/features/card-detail/ui/cardDetail.tsx
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/multi-step-form/components/AvartarImg.tsx
  src/features/multi-step-form/config/index.ts
  src/features/multi-step-form/hooks/queries/useUpdateCard.ts
  src/features/multi-step-form/hooks/queries/useUpdateCardInfo.ts
  src/features/multi-step-form/schema/index.ts
  src/features/multi-step-form/types/index.ts
  src/features/multi-step-form/ui/careerForm/firstStep.tsx
  src/features/multi-step-form/ui/careerForm/fourthStep.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/utils/index.tsx
Labels: auto approve, 🚀 feature

#306 [feat] 홈 화면 스와이프 적용
  src/app/globals.css
  src/features/card-notes/ui/memo/cardNotesMemoCard.tsx
  src/features/card-notes/ui/select/cardNotesCard.tsx
  src/features/home/containers/CardContainer.tsx
Labels: auto approve, ♻️ refactor

#303 Feat/share nearby
  src/app/share/page.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/share/components/JobLogo.tsx
  src/features/share/components/NearbyProfile.tsx
  src/features/share/containers/MyCardShareWithQrContainer.tsx
  src/features/share/containers/NearbyCardShareContainer.tsx
  src/features/share/containers/QrContainer.tsx
  src/features/share/containers/SegmentContainer.tsx
  src/features/share/hooks/mutations/usePostMyCard.ts
  src/features/share/hooks/queries/useNearbyCardQuery.ts
  src/features/share/hooks/useCurrentLocation.ts
  src/features/share/types/index.ts
Labels: auto approve

#308 [main] 주변 명함 공유 배포
  src/app/globals.css
  src/app/share/page.tsx
  src/features/card-notes/ui/memo/cardNotesMemoCard.tsx
  src/features/card-notes/ui/select/cardNotesCard.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/share/components/JobLogo.tsx
  src/features/share/components/NearbyProfile.tsx
  src/features/share/containers/MyCardShareWithQrContainer.tsx
  src/features/share/containers/NearbyCardShareContainer.tsx
  src/features/share/containers/QrContainer.tsx
  src/features/share/containers/SegmentContainer.tsx
  src/features/share/hooks/mutations/usePostMyCard.ts
  src/features/share/hooks/queries/useNearbyCardQuery.ts
  src/features/share/hooks/useCurrentLocation.ts
  src/features/share/types/index.ts
Labels: auto approve

#311 🐛 Fix: import 버그 수정
  src/app/(detail)/card-detail/[cardId]/page.tsx
Labels: auto approve

#313 🐛 Fix: 웹 환경 앱바 알림 아이콘 제거
  src/shared/ui/appbar.tsx
Labels: auto approve, 🚀 feature

#315 ✨ Feat: 흥미로운 명함, 한줄메모 뒤로가기 아이콘 웹뷰화면 최적화
  src/shared/ui/appbar.tsx
Labels: auto approve

#316 [deploy] 웹 최적화, 웹뷰 최적화
  next.config.mjs
  src/shared/ui/appbar.tsx
Labels: auto approve, ♻️ refactor, QA

#317 [Hotfix] 명함 생성 리로드, 스와이프 관련 이슈 해결
  src/features/home/containers/CardContainer.tsx
  src/features/home/containers/DraggableCard.tsx
Labels: auto approve, 🐛 bug, QA

#319 [deploy] 명함 위로 스와이프 시 주변 명함도 같이 올라가는 오류 수정
  src/features/home/containers/CardContainer.tsx
  src/features/home/containers/DraggableCard.tsx
Labels: auto approve

#320 ♻️ Refactor: 카카오톡 주석
  src/features/auth/login/ui/LoginFeature.tsx
Labels: auto approve

#323 [feat] 최종발표 QA 진행
  src/app/globals.css
  src/features/card-create/ui/index.tsx
  src/features/card-detail/ui/cardDetailHeader.tsx
  src/features/card-detail/ui/domain.tsx
  src/features/card-notes/components/Card.tsx
  src/features/home/components/BusinessCard/Card.tsx
  src/features/multi-step-form/schema/index.ts
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/careerForm/secondStep.tsx
  src/features/multi-step-form/ui/index.tsx
  src/features/share/components/ShareCard.tsx
  src/features/share/utils/getPreviewContent.ts
  src/shared/ui/Toast/sonner.tsx
  src/shared/ui/bottomModal/bottomModal.tsx
Labels: auto approve, QA

#325 [QA] QA 이것저것..
  src/app/(create)/card-create/loading.tsx
  src/app/(create)/card-create/new-card/loading.tsx
  src/app/(create)/card-create/new-card/multi-step-form/loading.tsx
  src/app/(detail)/card-detail/[cardId]/loading.tsx
  src/app/(notes)/card-notes/loading.tsx
  src/app/(notes)/card-notes/memo/loading.tsx
  src/app/(received)/received/choose/loading.tsx
  src/app/(received)/received/interesting/loading.tsx
  src/app/(received)/received/loading.tsx
  src/app/(received)/received/search/loading.tsx
  src/app/(share)/card-share/[id]/loading.tsx
  src/app/loading.tsx
  src/app/login/loading.tsx
  src/app/onboarding/loading.tsx
  src/app/page.tsx
  src/app/setting/alram-list/loading.tsx
  src/app/setting/alram/loading.tsx
  src/app/setting/loading.tsx
  src/app/setting/privacy-terms/loading.tsx
  src/app/setting/terms/loading.tsx
  src/app/setting/user-quit/loading.tsx
  src/app/share/loading.tsx
  src/app/share/page.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/home/containers/DraggableCard.tsx
  src/features/home/containers/HeaderContainer.tsx
  src/features/share/containers/SegmentContainer.tsx
  src/shared/providers/GlobalErrorBoundary.tsx
  src/shared/ui/appbar.tsx
Labels: auto approve, 🐛 bug, QA

#326 [Deploy] Merge develop to main
  src/app/(create)/card-create/loading.tsx
  src/app/(create)/card-create/new-card/loading.tsx
  src/app/(create)/card-create/new-card/multi-step-form/loading.tsx
  src/app/(detail)/card-detail/[cardId]/loading.tsx
  src/app/(notes)/card-notes/loading.tsx
  src/app/(notes)/card-notes/memo/loading.tsx
  src/app/(received)/received/choose/loading.tsx
  src/app/(received)/received/interesting/loading.tsx
  src/app/(received)/received/loading.tsx
  src/app/(received)/received/search/loading.tsx
  src/app/(share)/card-share/[id]/loading.tsx
  src/app/loading.tsx
  src/app/login/loading.tsx
  src/app/onboarding/loading.tsx
  src/app/page.tsx
  src/app/setting/alram-list/loading.tsx
  src/app/setting/alram/loading.tsx
  src/app/setting/loading.tsx
  src/app/setting/privacy-terms/loading.tsx
  src/app/setting/terms/loading.tsx
  src/app/setting/user-quit/loading.tsx
  src/app/share/loading.tsx
  src/app/share/page.tsx
  src/features/home/containers/CardContainer.tsx
  src/features/home/containers/DraggableCard.tsx
  src/features/home/containers/HeaderContainer.tsx
  src/features/share/containers/SegmentContainer.tsx
  src/shared/providers/GlobalErrorBoundary.tsx
  src/shared/ui/appbar.tsx
Labels: auto approve

#328 [Feat] 주변 명함 emptycase 추가
  public/icons/infoIcon.svg
  src/features/share/components/EmptyPeople.tsx
  src/features/share/containers/NearbyCardShareContainer.tsx
Labels: auto approve

#329 Merge develop to main
  public/icons/infoIcon.svg
  src/features/share/components/EmptyPeople.tsx
  src/features/share/containers/NearbyCardShareContainer.tsx
Labels: auto approve

#330 [QA] 최종발표 QA 2차 수정
  src/features/card-notes/components/Card.tsx
  src/features/home/components/BusinessCard/Card.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/index.tsx
  src/features/share/components/ShareCard.tsx
Labels: auto approve, QA

#331 [QA] 최종발표 QA 2차 수정
  src/features/card-notes/components/Card.tsx
  src/features/home/components/BusinessCard/Card.tsx
  src/features/multi-step-form/ui/careerForm/index.tsx
  src/features/multi-step-form/ui/index.tsx
  src/features/share/components/ShareCard.tsx
Labels: auto approve, QA

#332 [QA] QA 이것저것...
  src/app/page.tsx
  src/features/home/containers/DraggableCard.tsx
  src/features/home/containers/HeaderContainer.tsx
  src/features/received/ui/search/latestSearchKeyword.tsx
  src/features/share/containers/MyCardShareWithQrContainer.tsx
  src/shared/ui/appbar.tsx
Labels: auto approve, QA

#333 [Deploy] Merge develop to main
  src/app/page.tsx
  src/features/home/containers/DraggableCard.tsx
  src/features/home/containers/HeaderContainer.tsx
  src/features/received/ui/search/latestSearchKeyword.tsx
  src/features/share/containers/MyCardShareWithQrContainer.tsx
  src/shared/ui/appbar.tsx
Labels: auto approve

#334 🚑️ Hotfix: 홈화면 페이드인 삭제
  src/app/page.tsx
Labels: auto approve

#336 🚑️ Hotfix: 카카오 버튼 주석 해제
  src/features/auth/login/ui/LoginFeature.tsx
Labels: auto approve

#337 ㅇ
  src/features/auth/login/ui/LoginFeature.tsx
Labels: auto approve

#338 [fix] 알림 리스트 라우팅 수정, 온보딩 블루투스 텍스트 내주변으로 수정, 메인페이지 백그라운드 중앙 정렬
  src/app/page.tsx
  src/features/home/containers/HeaderContainer.tsx
  src/features/onboarding/config/slides.tsx
Labels: auto approve, 🐛 bug, ♻️ refactor, QA

#339 [deploy] 온보딩 블루투스 텍스트 내주변으로 수정
  src/app/page.tsx
  src/features/auth/login/ui/LoginFeature.tsx
  src/features/home/containers/HeaderContainer.tsx
  src/features/onboarding/config/slides.tsx
Labels: auto approve
